# This file is used to configure logging and agents behaviour.
#
# The first part consists of Wandb info used to log experiments.
# Changing it adjusts the way logging is stored and displayed.
#
# The second part (config) is used to change hyperparameter settings of agents.
# Changing it adjusts the way agents behave and learn.
project: "RL CartPole"
name: "PPO Discrete II"
dir: "../logs"
notes: "Testing algorithm functionality, logging and model saving -- discrete PPO."
mode: "online"
monitor_gym: "False"
config:
  environment: "CartPole-v1"                # Environment to use
  model: "discrete"                         # What kind of model to use?
  save_dir: "../models/"                    # Where to save model?
  save_name: "CartPole"                     # Model name
  save_interval: 25                         # How many previous episodes will be used to calculate mean reward?
  total_steps: 125000                       # For how many steps will the agent train?
  episode_steps: 999                        # How many steps before the episode is terminated?
  gamma: 0.99                               # Discount factor for future rewards
  lambda: 0.95                              # GAE tradeoff parameter
  ppo_epochs: 8                             # How many epochs to train on each episode?
  rollout_length: 2048                      # How many steps fit into one rollout?
  batch_size: 64                            # How many steps are in each batch?
  clip_epsilon: 0.2                         # How much is the policy clipped?
  learning_rate_shared: 0.0005              # Learning rate for shared layers
  learning_rate_actor: 0.0005               # Learning rate for actor head
  learning_rate_critic: 0.001               # Learning rate for critic head
  value_loss_coef: 0.5                      # How much is the value loss weighted?
  entropy_coef: 0.01                        # How much is the entropy loss weighted?