# This file is used to configure logging and agents behaviour
#
# The first part consists of Wandb info used to log experiments.
# Changing it adjusts the way logging is stored and displayed.
#
# The second part (config) is used to change hyperparameter settings of agents.
# Changing it adjusts the way agents behave and learn.
project: "My nice project name"
name: "HalfCheetah-v5 run"
dir: "../logs"
notes: "RUN?"
mode: "online"
monitor_gym: "False"
config:
  episodes: 5
  action_selection: "Random"